### ISSUE TITLE
On initialise I want to call redux store method

### ISSUE THREAD

**Issue by nil4you** [KaiHotz/React-Redux-Simple-Starter#4]
I tried to write read method of store asap application is initialised but I wasn't able to do it.

Not able to write code in app.js and index.js

Code structure is bit different so need guide in this case.

**Comment by KaiHotz** [comment]
I’m sorry but I didn’t understand what you intended to do and what the problem is. Could you please be more specific ?

**Comment by nil4you** [comment]
I have created local storage with auth token, as soon as application is initialised I want to redux action to grab that local storage if any.

Can’t find suitable place where I can write it. As boiler plate has bit different code in app.js

**Comment by KaiHotz** [comment]
You would need to do this in a componentDidMount lifecycle method probably in App.js. But I highly recommend that you don’t store auth token in local storage but instead use html cookies for that.

**Comment by KaiHotz** [comment]
This boilerplate doesn’t cover all the use cases there might be air there. It is for getting started with React and Redux in a very simple way, you should of course first get familiarized with React and Redux.

**Comment by nil4you** [comment]
I have written it life cycle hook in other componen but don’t know where I can put in app.js can you guide me ? As there is no component written in app.js

**Comment by KaiHotz** [comment]
I would  need to see your code. Can you share your project ?

**Comment by nil4you** [comment]
It's your code only.

https://raw.githubusercontent.com/KaiHotz/React-Redux-Simple-Starter/master/src/App.js
In simple terms, How I can write componentWillMount/componentDidMount in this file.

**Comment by KaiHotz** [comment]
There are 2 ways. 
One is you might convert this into a class component and then use componentDidMount. Please don't use componentWillMount since it will be deprecated on react.

The other way is with useEffect Hook that hats the same functionality as componentDidMount.

But i strongly recommend to you to first get better familiarised with React , learn more about components lifecycle method as well as about Class based and functional components.

**Comment by nil4you** [comment]
First approach is quite good. I am familiar with hooks and aware about depreciation of hook to unsafehook.

Was looking for what can be better way about it.
